# Generated by Django 5.2.5 on 2025-08-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "example_input",
                    models.TextField(help_text="Example input for the problem"),
                ),
                (
                    "example_output",
                    models.TextField(help_text="Expected output for the example"),
                ),
                (
                    "constraints",
                    models.TextField(blank=True, help_text="Problem constraints"),
                ),
                (
                    "hints",
                    models.TextField(
                        blank=True, help_text="Hints to solve the problem"
                    ),
                ),
                (
                    "template_code",
                    models.TextField(
                        default="def solution():\n    # Write your code here\n    pass",
                        help_text="Template code for users to start with",
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        default=list,
                        help_text="Test cases in JSON format: [{'input': '...', 'expected': '...'}, ...]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("successful_submissions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="questions.question"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
