# Generated by Django 5.0.8 on 2026-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_dailychallenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="questions.company"
            ),
        ),
    ]
