# Generated by Django 5.2.5 on 2026-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='topic_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
