# Generated by Django 5.2.5 on 2026-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
