# Generated by Django 4.2.26 on 2025-11-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_output', models.TextField(blank=True)),
                ('miri_trace', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
