# Generated by Django 5.2.5 on 2025-08-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("runtime_error", "Runtime Error"),
                            ("time_limit_exceeded", "Time Limit Exceeded"),
                            ("compilation_error", "Compilation Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "runtime",
                    models.FloatField(
                        blank=True, help_text="Runtime in seconds", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.IntegerField(
                        blank=True, help_text="Memory usage in KB", null=True
                    ),
                ),
                ("test_cases_passed", models.PositiveIntegerField(default=0)),
                ("total_test_cases", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("language", models.CharField(default="python", max_length=20)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
