# Generated by Django 5.2.5 on 2026-08-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_duration_weeks_course_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(blank=True, help_text="e.g., '7000/- + GST'", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='timing',
            field=models.CharField(blank=True, help_text="e.g., 'Weekend course, 4:00pm to 5:00pm'", max_length=200),
        ),
    ]
