# Generated by Django 5.2.5 on 2026-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_fee_course_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materials_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='recordings_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.CharField(blank=True, help_text="e.g., '12th Sep 2026'", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.CharField(blank=True, help_text="e.g., 'Kamal Kumar Mukiri'", max_length=200),
        ),
    ]
