# Generated by Django 5.2.5 on 2026-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_materials_info_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='training_mode',
            field=models.CharField(blank=True, help_text="e.g., 'Online'", max_length=100),
        ),
    ]
