# Generated by Django 5.2.5 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_update_visualise_stm32_persistent_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(choices=[('course', 'Course content'), ('hardware', 'Hardware and setup'), ('projects', 'Projects'), ('suggestion', 'Suggestion'), ('other', 'Other')], default='suggestion', max_length=20)),
                ('message', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
