# Generated by Django 5.2.5 on 2026-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='category',
            field=models.CharField(choices=[('debugging', 'Debugging Tools'), ('security', 'Security Tools'), ('observability', 'Observability Tools'), ('general', 'General Tools')], default='general', max_length=50),
        ),
    ]
