# Generated by Django 5.2.5 on 2026-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0002_devtool_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devtool',
            name='link',
        ),
        migrations.AddField(
            model_name='devtool',
            name='download_url',
            field=models.URLField(blank=True, help_text='Direct link to download the executable file'),
        ),
        migrations.AddField(
            model_name='devtool',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to the open-source repository'),
        ),
    ]
