# Generated by Django 5.2.5 on 2026-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0003_remove_devtool_link_devtool_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='requirements',
            field=models.TextField(blank=True, help_text="System dependencies, e.g., 'Linux Kernel 5.4+, Rust 1.70+'"),
        ),
        migrations.AddField(
            model_name='devtool',
            name='samples',
            field=models.TextField(blank=True, help_text='Sample code or CLI commands'),
        ),
    ]
