# Generated by Django 5.2.5 on 2026-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0003_remove_devtool_link_devtool_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='category',
            field=models.CharField(choices=[('debugging', 'Debugging Tools'), ('security', 'Security Tools'), ('observability', 'Observability Tools'), ('general', 'General Tools'), ('ai', 'AI Tools')], default='general', max_length=50),
        ),
    ]
