# Generated by Django 5.2.5 on 2026-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0004_alter_devtool_category'),
        ('devtools', '0004_devtool_requirements_devtool_samples'),
    ]

    operations = [
    ]
