# Generated by Django 5.2.5 on 2026-06-18 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0005_merge_20260616_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devtool',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='devtool',
            name='samples',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='devtools.devtool')),
            ],
        ),
    ]
