name: CI - Build and Deploy to Azure Web App (Container)

on:
  push:
    branches: [ main ]

# Explicit permissions are required to publish packages to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        # Recommended: create a Personal Access Token with `write:packages` and `read:packages`
        # and add it to repo secrets as GHCR_PAT. Using GITHUB_TOKEN may be blocked for some orgs.
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ghcr.io/${{ github.repository }}:latest
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
